INPUT:
  PIXEL_MEAN: [0., 0., 0.]
  PIXEL_STD: [1., 1., 1.]

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 16

OPTIM:
  NAME: "sgd"
  LR: 0.0005
  STEPSIZE: [20]
  MAX_EPOCH: 25

TRAINER:
  Uncertainty:
    G_ARCH: "Uncertainty"
    PROB: 0.5