INPUT:
  PIXEL_MEAN: [0., 0., 0.]
  PIXEL_STD: [1., 1., 1.]

DATALOADER:
  NUM_WORKERS: 1
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32

OPTIM:
  NAME: "sgd"
  LR: 0.001
  STEPSIZE: [20]
  MAX_EPOCH: 20

TRAINER:
  Uncertainty:
    G_ARCH: "Uncertainty"
    PROB: 0.5
