INPUT:
  PIXEL_MEAN: [0., 0., 0.]
  PIXEL_STD: [1., 1., 1.]

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32

OPTIM:
  NAME: "sgd"
  LR: 0.001
  STEPSIZE: [20]
  MAX_EPOCH: 18

TRAINER:
  SplitNet:
    G_ARCH: "FeatureSplitNet"
    SPLITNET: "SplitNet"
    WARMUP: 3
    LMDA: 0.3